language: cpp
# run on new infrastructure
sudo: false
cache: apt
# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - help2man
      - python-pexpect
      - libusb-1.0-0-dev
      - device-tree-compiler

env:
  global:
    - RISCV="/home/travis/riscv_install"
    - MAKEFLAGS="-j2"
    - PATH="$TRAVIS_BUILD_DIR/.build/riscv64-unknown-elf/buildtools/bin:$PATH"
    - PATH="/home/travis/riscv_install/bin:$PATH"

before_install:
  # make install destination
  - mkdir -p $RISCV
  # don't forget to clone riscv-tests/env
  - cd riscv-tests
  - git submodule update --init
  - cd ..
  # openocd also needs submodules
  - cd riscv-openocd
  - git submodule update --init
  - cd ..
  - unset CC CXX

# extra time duing long builds
install: travis_wait

# pexpect ends up in /usr/lib/python2.7/dist-packages, which is not part of the
# default python path.
script:
  - ./build.sh
  # Put compiler in expected place for debug tests
  - ln -s $TRAVIS_BUILD_DIR/.build/riscv64-unknown-elf/buildtools/bin/riscv64-unknown-elf-gcc $RISCV/bin
  - ln -s $TRAVIS_BUILD_DIR/.build/riscv64-unknown-elf/build/build-gdb-cross/gdb/gdb $RISCV/bin/riscv64-unknown-elf-gdb
  # Run debug tests.  Currently we expect 11 failures.
  - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages make -C riscv-tests/build debug-check | grep "11 tests returned fail"
